"""Add is_admin to User

Revision ID: 03445a5db846
Revises: 5f4f42812d44
Create Date: 2025-03-09 17:33:53.285965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03445a5db846'
down_revision = '5f4f42812d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
