"""Added read field to Notification

Revision ID: 4f9ea4d73b53
Revises: 7bf8e7a317c2
Create Date: 2025-03-20 20:00:19.633666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9ea4d73b53'
down_revision = '7bf8e7a317c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('read')

    # ### end Alembic commands ###
