"""Added tags to TriviaQuestion

Revision ID: 5f4f42812d44
Revises: 
Create Date: 2025-03-08 11:55:11.021332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4f42812d44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trivia_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trivia_question', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
