"""Added bonus field to QuizSession

Revision ID: 7bf8e7a317c2
Revises: 8696cd80cc3f
Create Date: 2025-03-20 14:09:41.195958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf8e7a317c2'
down_revision = '8696cd80cc3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_session', schema=None) as batch_op:
        batch_op.drop_column('bonus')

    # ### end Alembic commands ###
