"""Added answer_submitted field to QuizSession

Revision ID: 97ad920bdc68
Revises: 9d2222009a1c
Create Date: 2025-03-21 18:12:42.278479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ad920bdc68'
down_revision = '9d2222009a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers_submitted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_session', schema=None) as batch_op:
        batch_op.drop_column('answers_submitted')

    # ### end Alembic commands ###
